### ISSUE TITLE
Create categories folder outside from atomic-core folder.

### ISSUE THREAD

**Issue by rafaellyra** [nickberens360/atomic-docs#12]
To keep it simpler and easy to update, we should better separate core domain files from data domain files.

**Comment by webstractions** [comment]
Have to agree with this. I just installed and noticed that everything being developed is injected into the core file space.

**Comment by nickberens360** [comment]
@webstractions agreed on all counts. We are planning out the best approach to refactoring now.

**Comment by webstractions** [comment]
Nick, that would be great! 

I know you are a front end designer, and would like to help in the backend. Your app is a great concept, but needs a little work.

If you refactor, I am not sure where that would lead. I am working on a complete reimagination of your work here, basically to integrate into a Wordpress plugin. 

My problem is that I am not a front end guy. I don't know sass, more or less, pun intended.

Would be great if we can refactor this into something that can be used as stand alone, and seamlessly integrate into other software such as Wordpress,or other applications.

**Comment by adouglas** [comment]
I've had a stab at answering this in #26 (for the fllat branch).

@nickberens360 I'm interested in helping out, can you add andrew.douglas@trurating.com to the slack team.

**Comment by carstingaxion** [comment]
@nickberens360 Hello! I'm interested in joining your slack channel, too.
I did some work on the idea of bringing **Timber**, **twig** and **Atomic Docs** together (#13) and would be happy to share some ideas. Right now, I'm creating a test theme to showcase this to you.

**Comment by nickberens360** [comment]
@carstingaxion sounds great! What email should I use for the slack invite?

**Comment by carstingaxion** [comment]
@nickberens360 An invite for mail+atomicdocs.slack.com@carsten-bach.de would be nice!
