### ISSUE TITLE
Use composer to control php dependencies packages

### ISSUE THREAD

**Issue by rafaellyra** [nickberens360/atomic-docs#14]
To have better control/management of PHP lib dependencies we should use a [dependency manager](https://getcomposer.org/doc/00-intro.md).

**Comment by gavmck** [comment]
Are you guys likely to get on https://wpackagist.org/ ? Be cool to pull this in with composer too

**Comment by RobLoach** [comment]
In addition to being on Composer, it could be shipped as a stand-alone binary with https://getcomposer.org/doc/04-schema.md#bin
```
composer global require nickberens360/atomic-docs
```

> Are you guys likely to get on https://wpackagist.org/ ?

Composer indexes Packagist, so it would just need to be on https://packagist.org in order to be consumed by a Wordpress Composer set up.

**Comment by nickberens360** [comment]
@gavmck @RobLoach 

Hey guys, all great ideas. At the moment our focus is on refactoring the codebase.
