### ISSUE TITLE
Let's improve this !

### ISSUE THREAD

**Issue by xavierleune** [nickberens360/atomic-docs#32]
Hi @nickberens360 

My teammate @cssyren just show me this project. We find it very cool but we saw you're looking for PHP Dev contributors. As we need some improvements (like twig support and better integration with our environment) we'll be glad to help you with that !
Would be accept a pull request with that kind of changes and a few other ?

Thanks for your work,

**Comment by nickberens360** [comment]
Hi @xavierleune 

Thanks for your interest in the project! I've stopped dev on this version except for bug fixes. The new dev branch is v2_dev. I am almost done implementing the new features. If you'd like I'd definately take a look at the code there. It's only set up for Scss at the moment as i am still working on setting up the user configuration feature. 

New features include:
- Clicking in a code example brings up in browser code editing.
- You can drag and drop category names in the sidebar to re-order.
- You can drag and drop file names in the sidebar to re-order components and move them to different categories by dragging and dropping.
- Integrated a flat file database
