### ISSUE TITLE
CSS specificity and PHP include issues

### ISSUE THREAD

**Issue by dazgreer** [nickberens360/atomic-docs#35]
Hi, I'm using this for the first time, it seems great so far but I've run into a couple of issues.

1) I created a '.btn' component where the class is applied to the <a> tag. I specified a color for the text however this is being overridden (in the docs) by the '.atomsWrap a' style in the 'atomic-core/css/site.css' file since it has a higher specificity than just '.btn'.

<img width="983" alt="screen shot 2016-08-26 at 16 35 11" src="https://cloud.githubusercontent.com/assets/3962239/18009110/29205814-6bab-11e6-9fad-5e9659895dee.png">

2) Thinking about Atomic design, I would expect that I could create 'molecules' within the docs by using includes from separate 'atom' components to build them up (to save from repeating code). However the includes are being parsed as text. I sit possible to do this?

<img width="747" alt="screen shot 2016-08-26 at 16 34 43" src="https://cloud.githubusercontent.com/assets/3962239/18009118/33e346bc-6bab-11e6-81e0-6a204ca36c2b.png">

Thanks, Daz

**Comment by nickberens360** [comment]
@dazgreer thanks for the input. I updated atomic docs to remove the <a> tag styling, thanks for the heads up! You can replace the /atomic-core directory on your install with the latest download from the repo. Alternatively you could open /atomic-core/scss/_cleanup.scss and remove the a{} style definition and rerun gulp.

And yeah I'm working on adding a third tab that will show the actual html output instead of any dynamic code.

**Comment by dazgreer** [comment]
Thanks Nick, that's great, looking forward to the 3rd tab!

**Comment by nickberens360** [comment]
@dazgreer the latest version of master has a third tab labeled "output" which will display the outputted html if you're using php or another dynamic language.

**Comment by dazgreer** [comment]
@nickberens360 I've done a fresh install of this to test it out and I can see the third 'output' box which is great but for the example I first posted which has 3 php includes, I don't get any output. Pretty sure the relative URLs are correct, any ideas what might be wrong? All the info is in the image in the OP. Cheers

**Comment by nickberens360** [comment]
Ahh yes, use the following syntax for your includes 

<?php include __DIR__ . '/components/atoms/box.php'; ?>

**Comment by dazgreer** [comment]
@nickberens360 thanks I've set this up as per below but they're still not showing:

<?php include DIR . '/components/atoms/box.php'; ?>
<?php include DIR . '/components/atoms/paragraph.php'; ?>
<?php include DIR . '/components/atoms/button.php'; ?>

The actual files are at e.g. 'http://localhost:8888/atomic-docs-master/components/atoms/box.php'. Where is DIR defined or do I need to set it?

Cheers

**Comment by nickberens360** [comment]
Sorry, I had a syntax error. I forgot the double underscores

<?php include __DIR__ . '/components/organisms/slider.php'; ?>

**Comment by nickberens360** [comment]
Hmm, there should be double underscores before and after __DIR__

For some reason github removes them when I save the comment. See the image for the right syntax.

![capture](https://cloud.githubusercontent.com/assets/1283934/18788968/a3bfb2b2-816e-11e6-908f-4b0c27b13439.PNG)

**Comment by dazgreer** [comment]
@nickberens360 tried the double underscores and still not getting any output

<img width="874" alt="screen shot 2016-09-26 at 11 45 21" src="https://cloud.githubusercontent.com/assets/3962239/18829997/178e81e2-83df-11e6-82fe-ba0996f5b0f9.png">

<img width="870" alt="screen shot 2016-09-26 at 11 45 38" src="https://cloud.githubusercontent.com/assets/3962239/18829996/178c3306-83df-11e6-8b23-a7e848c81cf9.png">

**Comment by nickberens360** [comment]
Huh, I'm at a loss. Could you possibly zip up your project and send it to me so I can take a closer look? That really should be working, hmmm. My email is nickberens360@gmail.com

**Comment by dazgreer** [comment]
thanks @nickberens360 have sent you an email

**Comment by nickberens360** [comment]
@dazgreer Ok, I'm an idiot. The path I gave you in the include would work if you were in the root of your project. Try the path that is shown in this screenshot.
![image](https://cloud.githubusercontent.com/assets/1283934/18844377/a7f5c8a0-83e2-11e6-897a-1c932109e07d.png)

**Comment by dazgreer** [comment]
@nickberens360, that works, thanks for all your help on this!

**Comment by nickberens360** [comment]
@dazgreer no problem, and thanks for checking the project!
