### ISSUE TITLE
( ! ) Notice: Undefined index: 

### ISSUE THREAD

**Issue by MeLeGe** [nickberens360/atomic-docs#36]
I found this error in the index page only ?

`( ! ) Notice: Undefined index: cat in C:\wamp64\www\atomic-docs\atomic-core\index.php on line 62 Call Stack #TimeMemoryFunctionLocation 10.0007312400{main}( )...\index.php:0 " data-navitem="readme">
`

**Comment by nickberens360** [comment]
@MeLeGe Hey thanks for the heads up. Issue resolved.
