### ISSUE TITLE
Permission on edit

### ISSUE THREAD

**Issue by romago** [nickberens360/atomic-docs#38]
Hi Nick.
How I can close style-guide page (atomic-core) from edit?

**Comment by nickberens360** [comment]
@romago I am working on a solution for this currently. I will let you know when I have solved this

**Comment by nickberens360** [comment]
@romago In the latest version, go to atomic-core/footer.php and uncomment the following include on line 184.

<?php 
  //Uncomment the following include to enable client mode.
  //include "clientmode.php" 
?>

This will turn off all editor functionality.

**Comment by romago** [comment]
It works. Thanks a lot.

I added little bit script for remove hidden element.
`$('#atomsWrap .clientMode .aa_actionDrawer, #atomsWrap .clientMode .fa-pencil-square-o, #atomsWrap .clientMode .atomic-editor-footer, #atomsWrap .clientMode .copyBtn-edit, #atomsWrap .clientMode .aa_addFile, #atomsWrap .clientMode .catAdd').remove();`
