### ISSUE TITLE
Issues with sync and  need of postcss support

### ISSUE THREAD

**Issue by gemini1988** [nickberens360/atomic-docs#39]
Hello nick,

This is really awesome style guide. Great job !

I have been using it for first time & have faced some issues. 

1. I have clone of your repo. when i have run it i am not able to see some options like renaming, moving , drag and drop is not working,

 **localhost UI**

![localhost](https://cloud.githubusercontent.com/assets/16187886/20513724/e0315a98-b0ad-11e6-8a4f-e8268f008994.JPG)

**Your Demo UI** ( http://www.nickberens.me/atomic-docs/atomic-core/base.php )

![demo](https://cloud.githubusercontent.com/assets/16187886/20513773/2e3d1876-b0ae-11e6-9f08-63ef3930842a.JPG)

you can see how the interface (icons and options) are different.

2. *.scss extension is not getting added to import , when we create categories

![ext](https://cloud.githubusercontent.com/assets/16187886/20513844/a66dd4d4-b0ae-11e6-8bee-9d10855d3fbb.JPG)

3. I am also facing an issue when i deleted a category but its not reflecting automatically , I need to go to atomic-db -> components and delete related code to make it work.

4. need postcss support

**Comment by nickberens360** [comment]
@gemini1988 thanks for checking out the project!

1) The demo version and the latest version have changed quite a bit. To rename a component click the edit icon next to the component name in the main area not in the sidebar.
![ad](https://cloud.githubusercontent.com/assets/1283934/20543252/952b82d4-b0c2-11e6-804e-f890587fdc4d.jpg)

2) .scss file extension is not required for @import strings. From the Sass docs
http://sass-lang.com/guide
"Notice we're using @import 'reset'; in the base.scss file. When you import a file you don't need to include the file extension .scss. Sass is smart and will figure it out for you. "

3) I have never experienced issues when deleting a category and not having it removed from the atomic-db. Is it creating categories correctly for you?

I will download the latest and test on my end. Thanks for the feedback!

**Comment by nickberens360** [comment]
@gemini1988 Everything seems to be working fine on my end. If you get a chance can you zip up your project and send it to me so I can debug further?

**Comment by gemini1988** [comment]
Hey nick,
 
Great , Thanks for quick response. 👍 

1) Yeah that rename feature works 👍 . In latest version drag & drop or move feature is not available. ?

2)  regarding .scss extension : it was issue on my end , I was configuring with postcss, now i got it fixed myself using postcss-sassy-import in gulp file.

3) Sorry ,  This issue happened while deleting component because i include special character. Every thing else is working fine 👍

**Comment by nickberens360** [comment]
@gemini1988 Drag and drop should definitely be working. Are there any errors in the console?

**Comment by gemini1988** [comment]
I am able to order the components within same category, but when i trying to drag component from a category to other category, its not working. i don't see any errors.

**Comment by nickberens360** [comment]
@gemini1988 Hey sorry for the late reply. The sorting works on my end. There is a bug though. If you click a component's link in the sidebar it loses it's drag and drop functionality. Try sorting on a fresh reload.
