### ISSUE TITLE
Prevent access or prevent editing of files on a live site?

### ISSUE THREAD

**Issue by ChristofLee** [nickberens360/atomic-docs#40]
**Question**
What's the best way to manage atomic docs on a live website?

**Example**
For example, if I have a Wordpress website utilising Atomic Docs, and is deployed through Git, how can I prevent someone from opening Atomic Docs and making changes? 

(Git ignoring the atomic core could be a solution but then I would not be able to view the docs)

Is there a setting within Atomic Docs to prevent editing of the files on a live site?

**In practice**
I have seen in your [demo](http://www.nickberens.me/atomic-docs/atomic-core/) you have disabled editing, so that noone is able to make changes to your demo.

Any help with this issue would be much appreciated.

**Comment by nickberens360** [comment]
@ChristofLee So there are a couple different options. 

1) If you want to completely block access to Atomic Docs you can download the following wordpress plugin. It requires you to be logged in as an administrator to view the styleguide.
https://wordpress.org/plugins/atomic-docs-lockdown/

2) If you'd like people to still be able to view the styleguide but not make edits you can go into atomic-core/footer.php and uncomment the line on 181. This will enable "Client Mode" which will turn off all editing capabilities and put Atomic Docs into view only.

<?php 
  //Uncomment the following include to enable client mode.
  //include "clientmode.php" 
?>

**Comment by ChristofLee** [comment]
That is exactly what I was looking for, thanks Nick.

I love Atomic Docs, its awesome!

**Comment by nickberens360** [comment]
@ChristofLee Great, thanks for checking out the project!!
