### ISSUE TITLE
Installed fine but doesn't want to create new components or write settings changes.

### ISSUE THREAD

**Issue by melanieceraso** [nickberens360/atomic-docs#45]
Hey guys.
I just installed atomic docs and am having troubles with changing any of the settings or creating new components.  Anytime I try to change something, I'm getting a permissions error.

`Object {readyState: 4, responseText: "<br />↵<b>Warning</b>:  file_put_contents(/Users/m…s.php</b> on line <b>14</b><br />↵can't open file", status: 200, statusText: "OK"}`

Can anyone lend any help with this?  Thanks.

**Comment by melanieceraso** [comment]
Figured out it was a file permission issue.  Thx.

**Comment by nickberens360** [comment]
@melanieceraso glad you're up and running, and thanks for checking out the project!
