### ISSUE TITLE
location of the generated js files

### ISSUE THREAD

**Issue by tolusonaike** [nickberens360/atomic-docs#47]
Wanted to get clarification on this. Will it be useful to have the generated js files landing is the scss folder instead? Since the assumption is that a precompiler will compile the css, the precompiler will probably also compile the js.

**Comment by tolusonaike** [comment]
Aaand of course i just noticed the settings.dat file that stores locations. Closing this issue

**Comment by nickberens360** [comment]
Ha, yeah if you click the gear icon in the upper left blue toolbar you can change settings there as well.

**Comment by nickberens360** [comment]
Ha, yeah if you click the gear icon in the upper left blue toolbar you can change settings there as well.

**Comment by tolusonaike** [comment]
It doesn't have a js option though

**Comment by nickberens360** [comment]
Ahh yes, right you are. I'll have to add that to my to do list. Thanks for the feedback and checking out the project.
