### ISSUE TITLE
Integration with JS / AngularJS Projects?

### ISSUE THREAD

**Issue by bdenham** [nickberens360/atomic-docs#49]
Even though it's PHP-based, I'd love to get some help/direction for somehow integrating this into a variety of different JS-based apps, including my current AngularJS app. Is this at all possible? I'll try any workaround you might suggest. Thanks.

**Comment by nickberens360** [comment]
@bruce I have about zero experience with angular, but the flat bd that
stores all the data is just a big Jason file, which is how angular consumes
and displays data if my wild guess is right so I'm sure it could work with
some tweaking.

**Comment by nickberens360** [comment]
@bruce also the code base is pretty happhazardly put together. I'm a
designer and from end dev, so there really no Mvc organization or any code
structure paradigm behind it so it's a bit of a mess

**Comment by bdenham** [comment]
Ok, thanks for getting back to me. As long as I can point the atomic docs output to directories consumed/used in my angular app, I guess it should work. I'm just wondering if all the modules and sass source files will need to live in a completely separate project, running with MAMP, and then maybe just automate the output (main.css) to the angular projects. That may be the best I can do.
