### ISSUE TITLE
Unable to show sidebar after it has been hidden.

### ISSUE THREAD

**Issue by dallasantwerp** [nickberens360/atomic-docs#51]
It seems the button with class '.atoms-side_show ' stays on 'display: none' if the sidebar is hidden.
The functions showSideBar() and hideSideBar() don't contain a toggle for it.
Or always leaving it to 'display: block' would be a fix too.

Alsow the target element is quite small to click. You realy have to click on the arrow.
A solution would be to put the class '.js-showSide' on the parent.

**Comment by nickberens360** [comment]
@dallasantwerp yeah I've been meaning to fix that. Thanks

**Comment by nickberens360** [comment]
@dallasantwerp fixed
