### ISSUE TITLE
Sass preprocessing output?

### ISSUE THREAD

**Issue by qwer4k** [nickberens360/atomic-docs#56]
Hello there again,

I am very new on sass and first time i use atomic-docs.  I have a display problem, i can't see the preview. styles are not applied to output.

[Here is the screenshot.](https://prnt.sc/im3h4v)

i think problem is about **Configure your preprocessor to output scss/main.scss to css/main.css.**

- i use wamp and localhost i working fine.
- i installed Ruby and installed SASS with cmd.
- i tried to configure the preprocessor like this command with cmd.

`C:\Wamp64\www\ui-kit>Sass scss/main.scss css/main.css`

So i am sure that i cannot make output regularly but it was first time i installed Ruby and Sass. So please can you describe me very very clear ( like telling idiot :) ) what should i do about output.

Thanks a lot

**Comment by qwer4k** [comment]
solved again.

**Comment by mjs2430** [comment]
Hi @qwer4k , I'm having the same issue. My preprocessor works fine and updates my files, but I am unable to see the styling affect the preview as well. How did you fix this?

Thanks

**Comment by nickberens360** [comment]
@qwer4k so you are unable to see the updated styles in the atomic docs styleguide or the front end of your site?
