### ISSUE TITLE
Use a javascript build tool 

### ISSUE THREAD

**Issue by rafaellyra** [nickberens360/atomic-docs#7]
Hi,

I am trying to use atomic-docs in a project that I am currently working but for this I need to make it work with less (preprocessor), I don't know how you guys are building the JS (concat and minify) but maybe it could use grunt, gulp, make or anything else to do it, it would also make possible to not push the builded file as well.

If you guys think it is a good idea I able to help making pull requests.

**Comment by nickberens360** [comment]
Hi @rafaellyra 

Unfortunately LESS is not supported at the moment.

As far as concatenating and minifying the JS files. Are you referring to the files located in /atomic-core/js?, or the project root js files /js?

**Comment by rafaellyra** [comment]
Hi @nickberens360 

Actually, I am doing the changes to support LESS in my fork (depending on how I can do it, I can make a PR for this also), I am referring to the /atomic-core/js files.

**Comment by nickberens360** [comment]
@rafaellyra 

Ok, that would be great. Just to warn you, I'm more of a designer than a programmer. The code for this is probably a little rough:)

I am almost done setting up gulp in /atomic-core/js. I'll let you know as soon as I push it.

**Comment by nickberens360** [comment]
@rafaellyra 

in master, gulp has been added to handle all of the js and scss in atomic-core/

**Comment by nickberens360** [comment]
@rafaellyra 

I created a branch named "less". I believe less should compile properly now. If you have the time would you mind checking it out and seeing if it's working properly for you?

In atomic-config.php you can set the "preCssExt" variable to "less". This should now be enough for LESS to work.

  $config['preCssDir'] = 'less'; //Scss preprocessor directory name. E.G sass
  **$config['preCssExt'] = 'less';** //prerocessed file ext. E.G. scss
  $config['compExt'] = 'php'; //markup file ext. E.G. html, twig, etc...

**Comment by rafaellyra** [comment]
@nickberens360 

Great! I took a look at your changes, I already did something similar in my customizing, but there are still some stuff to really work properly with less, for instance:
- the way that `less include` works is not smart as sass/scss (the _ before the filename pattern doest not work on less)
- there are some php functions that the name are specific for the preprocessor like: `createScssCatDirAndFile`

I am working on it and I can open a PR if you would like, I don't know what are your plans for this project but I could help you with some code improvement, there are some simple changes that we could to make the project more reusable/generic and the code easier to read like make this php functions more generic/configurable or even support kind of plugins to add features like have css as default styles language and preprocessor support done by plugin installing (atomic-docs-less, atomic-docs-scss, atomic-docs-stylus, ...) and use a template language to improve the code readability separating template from logic like [here](https://github.com/nickberens360/atomic-docs/blob/master/atomic-core/partial-mngr/functions/cat-create-functions.php#L68).

by the way, you can close this issue, just let me know what do you think about technical improvements suggestions,  and thanks for all your help :)
