### ISSUE TITLE
Components as template files?

### ISSUE THREAD

**Issue by cdCorey** [nickberens360/atomic-docs#8]
All the examples show the components as HTML files. Is it necessary for them to be HTML, or can this support PHP or other template languages?

**Comment by rafaellyra** [comment]
acctualy they are already php files by default as you can see in the [box sample](https://github.com/nickberens360/atomic-docs/blob/master/components/modules/boxes.php), but I think that would be a good improvement to use a template language as twig or something else

**Comment by nickberens360** [comment]
@cdCorey and @rafaellyra 

In atomic-config.php you can set the component extension to whatever you'd like. 

$config = array();
  $config['dir'] = dirname(__FILE__);

  //user defined varibales
  $config['preCssDir'] = 'scss'; //Scss preprocessor directory name. E.G sass
  $config['preCssExt'] = 'scss'; //prerocessed file ext. E.G. scss
  **$config['compExt'] = 'php'; //markup file ext. E.G. .html**

  return $config;

**Comment by cdCorey** [comment]
Excellent. In the videos it showed a .html extension, which is why I was unsure.

I assume the intention is mainly to be able to display the component in the style guide, but ideally it would be great to use the component files directly in live site templates (to keep it DRY). I imagine there could be problems with displaying in the style guide if you use a template type AtomicDocs isn't designed for, though. Would it make sense to support plugins to AtomicDocs to process different template languages, or something like that?

**Comment by nickberens360** [comment]
@cdCorey 

In theory, you can give access to your application's functions and data in atomic-head.php. Then you should be able to use your templating language in the components.

I do this with WordPress sites all the time by including wp-load.php in atomic-head.php giving me access to wp's functions. Then I can use the wp_query function, for example, in my components.

Then I just include that component in my theme wherever I need it. Both AtomicDocs and wherever I include the component will remain up to date.

**Comment by cdCorey** [comment]
Booya.


--
Corey Caswick
Chatman Design
chatmandesign.com <http://www.chatmandesign.com>
